version: '3.8'
services:

  php:
    image: willianvalerio/dd-php
    container_name: php
    working_dir: /var/www/html
    volumes:
      - type: bind
        source: ./
        target: /var/www/html
    networks:
      - app-network
    ports:
      - "8000:80"    

  mongo:
    image: mongo
    container_name: mongo
    ports:
     - "27017:27017"
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge